config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :apextransactions
  devise_for :users
  resources :savings
  resources :loans
  resources :transactions
  resources :clients
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/apextransactions_controller.rb
class ApextransactionsController < ApplicationController
  before_action :set_apextransaction, only: %i[ show edit update destroy ]

  # GET /apextransactions or /apextransactions.json
  def index
    @apextransactions = Apextransaction.all
  end

  # GET /apextransactions/1 or /apextransactions/1.json
  def show
  end

  # GET /apextransactions/new
  def new
    @apextransaction = Apextransaction.new
  end

  # GET /apextransactions/1/edit
  def edit
  end

  # POST /apextransactions or /apextransactions.json
  def create
    @apextransaction = Apextransaction.new(apextransaction_params)

    respond_to do |format|
      if @apextransaction.save
        format.html { redirect_to @apextransaction, notice: "Apextransaction was successfully created." }
        format.json { render :show, status: :created, location: @apextransaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @apextransaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apextransactions/1 or /apextransactions/1.json
  def update
    respond_to do |format|
      if @apextransaction.update(apextransaction_params)
        format.html { redirect_to @apextransaction, notice: "Apextransaction was successfully updated." }
        format.json { render :show, status: :ok, location: @apextransaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @apextransaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apextransactions/1 or /apextransactions/1.json
  def destroy
    @apextransaction.destroy
    respond_to do |format|
      format.html { redirect_to apextransactions_url, notice: "Apextransaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apextransaction
      @apextransaction = Apextransaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def apextransaction_params
      params.require(:apextransaction).permit(:description, :time, :transaction_id)
    end
end

app/helpers/apextransactions_helper.rb
module ApextransactionsHelper
end

app/views/apextransactions/_form.html.erb
<%= form_with(model: apextransaction) do |form| %>
  <% if apextransaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apextransaction.errors.count, "error") %> prohibited this apextransaction from being saved:</h2>

      <ul>
        <% apextransaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.datetime_select :time %>
  </div>

  <div class="field">
    <%= form.label :transaction_id %>
    <%= form.text_field :transaction_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apextransactions/edit.html.erb
<h1>Editing Apextransaction</h1>

<%= render 'form', apextransaction: @apextransaction %>

<%= link_to 'Show', @apextransaction %> |
<%= link_to 'Back', apextransactions_path %>

app/views/apextransactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apextransactions</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Time</th>
      <th>Transaction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apextransactions.each do |apextransaction| %>
      <tr>
        <td><%= apextransaction.description %></td>
        <td><%= apextransaction.time %></td>
        <td><%= apextransaction.transaction_id %></td>
        <td><%= link_to 'Show', apextransaction %></td>
        <td><%= link_to 'Edit', edit_apextransaction_path(apextransaction) %></td>
        <td><%= link_to 'Destroy', apextransaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apextransaction', new_apextransaction_path %>

app/views/apextransactions/new.html.erb
<h1>New Apextransaction</h1>

<%= render 'form', apextransaction: @apextransaction %>

<%= link_to 'Back', apextransactions_path %>

app/views/apextransactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @apextransaction.description %>
</p>

<p>
  <strong>Time:</strong>
  <%= @apextransaction.time %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @apextransaction.transaction_id %>
</p>

<%= link_to 'Edit', edit_apextransaction_path(@apextransaction) %> |
<%= link_to 'Back', apextransactions_path %>