config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :apextransactions
  devise_for :users
  resources :savings
  resources :loans
  resources :transactions
  resources :clients
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    today = Date.today

   

  end



end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 h-100 sticky-top" style="width: 300px; background-color:#c8cacc;">
    <%= image_tag("Apex Logo 1.png", alt: "logo", size: "250x250", class: "like_image_for_index rounded") %>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto d-grid gap-1"> 
      
    	<li class="nav-item ms-2">
        <%= link_to 'HOME', root_path, class:"fs-6 btn btn-sm fw-bold"%>
	    </li>

      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle fs-6 text-dark btn-sm fw-bold" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
            CREATE
          </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'NEW TRANSACTION', new_transaction_path, class:"dropdown-item"%></li>
              <li><%= link_to 'NEW LOAN', new_loan_path, class:"dropdown-item"%></li>
              <li><%= link_to 'NEW SAVINGS ACOUNT', new_saving_path, class:"dropdown-item"%></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'NEW CLIENT', new_client_path, class:"dropdown-item"%></li>
            </ul>
      </li>

      <li class="nav-item ms-2">
        <%= link_to 'TRANSCATIONS', transactions_path, class:"fs-6 btn btn-sm fw-bold"%>
      </li>
      <li class="nav-item ms-2">
        <%= link_to 'LOANBOOK', loans_path, class:"fs-6 btn btn-sm fw-bold"%>
      </li>
      <li class="nav-item ms-2">
        <%= link_to 'SAVING BOOK', savings_path, class:"fs-6 btn btn-sm fw-bold"%>
      </li>
      <li class="nav-item ms-2">
        <%= link_to 'CLIENTS', clients_path, class:"fs-6 btn btn-sm fw-bold"%>
      </li>
      <li class="nav-item ms-2">
        <%= link_to 'ACCOUNTS', accounts_path, class:"fs-6 btn btn-sm fw-bold"%>
      </li>
    
    <br/> <br/>

      <li class="nav-item ms-2">
        <%= link_to 'ABOUT', home_about_path, class:"fs-6 btn btn-sm fw-bold"%>
      </li>
    </ul>

    <hr>
    <ul class="nav nav-pills flex-column mb-auto"> 

      <li class="nav-item dropup">
          <a class="nav-link dropdown-toggle fs-6 text-dark btn-sm fw-bold" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
            ACCOUNT
          </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'EDIT USER', edit_user_registration_path, class:"dropdown-item"%></li>
              <li><%= link_to 'SIGN UP', new_user_registration_path, class:"dropdown-item"%></li>
              <li><%= link_to 'SIGN IN', new_user_session_path, class:"dropdown-item"%></li>
               <li><hr class="dropdown-divider"></li>
              <li><%= button_to 'LOG OUT', destroy_user_session_path, method: :delete, class:"dropdown-item"%></li>
              
            </ul>
      </li>
    </ul>
</div>

app/views/home/_splashpage.html.erb
<h3><%= link_to 'SIGN UP', new_user_registration_path, class:"dropdown-item"%></h3>
<h3><%= link_to 'SIGN IN', new_user_session_path, class:"dropdown-item"%></h3>
              

app/views/home/index.html.erb
<% if user_signed_in? %>
	<h1>Home#index</h1>
	<p>Find me in app/views/home/index.html.erb
	.

	.
	.







	</p>
<% else %>
	<div class= "card text-center w-90" style="background-color:#c8cacc">	
		<%= image_tag("Apex Logo 1.png", alt: "logo", class: "like_image_for_index rounded") %>
		<br/>
		<h2><%= link_to 'SIGN IN', new_user_session_path, class:"btn btn-dark"%> </h2>
	</div>
<br/><br/>
	<%= link_to 'New Account', new_user_registration_path, class:"btn btn-sm btn-secondary position-absolute bottom-0 end-0"%>
<% end %>