config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :apextransactions
  devise_for :users
  resources :savings
  resources :loans
  resources :transactions
  resources :clients
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:form, :category, :doc_ref, :amount, :type, :account_id, :loan_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<form>
  <div class="mb-3">
         <% form.label :form %>
         <%= form.text_field :form, class:"form-control", placeholder:"Format" %>
  </div>

  <h5>account</h5>
  <%=form.collection_select(:account_id, Account.all, :id, :id, prompt: true )%>
</br></br></br>


<h5>account</h5>
  <%=form.collection_select(:loan_id, Loan.all, :id, :id, prompt: true )%>
</br></br></br>

 




       
  </div>
  
   




  <div class="mb-3">
         <% form.label :doc_ref %>
         <%= form.text_field :doc_ref, class:"form-control", placeholder:"Document Ref" %>
  </div>

   <div class="mb-3">
         <% form.label :amount %>
         <%= form.text_field :amount, class:"form-control", placeholder:"Transaction Amount" %>
  </div>

 
  <div class="actions">
    <%= form.submit class: 'btn btn-secondary' %>
  </div>

</form>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>
<br/>
<%= render 'form', transaction: @transaction %>
<br/>
<%= link_to 'Show', @transaction, class:"btn btn-secondary" %>
<%= link_to 'Delete', @transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
<%= link_to 'Back', transactions_path, class:"btn btn-dark" %>

app/views/transactions/index.html.erb
<div class="p-3" style="background-color:#dee1e3;">
  <div class="p-4 bg-light"> 

    <h1>Transactions</h1>

    <table class="table table-striped table-hover table-bordered">
        <thead class="table-dark">
        <tr>
          <th>Form</th>
          <th>Category</th>
          <th>Account</th>
          <th>Loan</th>
          <th>Doc ref</th>
          <th>Amount</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @transactions.each do |transaction| %>
          <tr>
            <td><%= transaction.form %></td>
            <td><%= transaction.category %></td>
            <td><%= transaction.account_id %></td>
            <td><%= transaction.loan.client.sur_name %></td>
            <td><%= transaction.doc_ref %></td>
            <td><%= transaction.amount %></td>
            <td><%= link_to 'Show', transaction %></td>
            <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
            <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Transaction', new_transaction_path,class:"btn btn-secondary" %>
  </div>
</div>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>
</br>
<%= render 'form', transaction: @transaction %>
</br>
<%= link_to 'Back', transactions_path, class: "btn btn-dark" %>

app/views/transactions/show.html.erb
<div class="card w-75 bg-light ps-5">
  <div class="card-body p-5 align-middle">
  </br></br>
    <% if false %> <h5 class="card-title fs-1"><%=@client.sur_name %> <%= @client.first_name %> <%= @client.other_name %></h5> <% end %>
    
    <h5 class="card-title fs-1"><%= @transaction.amount %></h5> 
    <p class="card-text fs-4">Transaction Form: <%= @transaction.form %> | Transaction Category: <%= @transaction.category %> | Account: <%= @transaction.account %> </p>
    <p class="card-text fs-4">Transaction Doc Ref: <%= @transaction.doc_ref %> </p>
   
    
    </br>
    <%= link_to 'Edit', edit_transaction_path(@transaction), class:"btn btn-secondary" %> 
    <%= link_to 'Delete', @transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
    <%= link_to 'Back', transactions_path, class:"btn btn-dark" %>

  </div>
</div>